# Dockerfile for Nginx avec ModSecurity
FROM nginx:latest

# Copie des fichiers HTML et JavaScript
COPY index.html /usr/share/nginx/html/
COPY pong.js /usr/share/nginx/html/
COPY ManualPlayer.js /usr/share/nginx/html/
COPY AI.js /usr/share/nginx/html/

# Génération du certificat SSL
RUN openssl req -x509 -nodes -days 365 -newkey rsa:4096 -keyout /etc/ssl/private/nginx.key -out /etc/ssl/certs/nginx.crt -subj "/C=FR/ST=Occitanie/L=Perpignan/O=42/CN=localhost";

# Copie de la configuration Nginx avec ModSecurity
COPY nginx.conf /etc/nginx/nginx.conf

# Copie du fichier de règles ModSecurity
COPY modsecurity.conf /etc/nginx/modsecurity.conf

# Exposition du port 80
EXPOSE 80

# Démarrage de Nginx
CMD ["nginx", "-g", "daemon off;"]