# Generated by Django 4.2.9 on 2024-01-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_tournament_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
