# Generated by Django 4.2.9 on 2024-01-30 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_tournament_number_registered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='active',
            new_name='subscribe_active',
        ),
    ]
