# Generated by Django 4.2.9 on 2024-01-30 13:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_active_tournament_subscribe_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
