# Generated by Django 4.2.9 on 2024-01-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tournament_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
