# Generated by Django 4.2.9 on 2024-02-01 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tournament_running'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1_name', models.CharField(default='player 1', max_length=100)),
                ('player1_score', models.IntegerField(default=0)),
                ('player2_name', models.CharField(default='player 2', max_length=100)),
                ('player2_score', models.IntegerField(default=0)),
                ('played', models.BooleanField(default=False)),
                ('winner', models.CharField(default='', max_length=100)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
