# Generated by Django 4.2.9 on 2024-02-01 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(default='/static/images/no_image.png', upload_to='', verbose_name='Photo de profil'),
        ),
    ]
