# Generated by Django 4.2.9 on 2024-02-01 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_user_profile_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='host',
        ),
        migrations.AddField(
            model_name='user',
            name='historic',
            field=models.ManyToManyField(blank=True, to='home.match'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(upload_to='', verbose_name='Photo de profil'),
        ),
    ]
