# Generated by Django 4.2.9 on 2024-02-02 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_remove_match_host_user_historic_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='players_registered',
        ),
        migrations.AddField(
            model_name='tournament',
            name='players_registered',
            field=models.TextField(blank=True),
        ),
    ]
