# Generated by Django 4.2.9 on 2024-02-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_tournament_players_registered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='from_tournament',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='remaining_match',
            field=models.ManyToManyField(to='home.match'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='remaining_players',
            field=models.TextField(blank=True),
        ),
    ]
