# Generated by Django 4.2.9 on 2024-02-06 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_match_from_tournament_tournament_remaining_match_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='all_match',
            field=models.ManyToManyField(related_name='all_match', to='home.match'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='remaining_match',
            field=models.ManyToManyField(related_name='remaining_match', to='home.match'),
        ),
    ]
